services:
  - type: web
    name: iso-tank-api
    env: python
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"   # Ensure you're using the correct Python version
    buildCommand: |
      python -m venv .venv
      ./.venv/bin/pip install -r requirements.txt
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    healthCheckPath: /health   # Optional, add if you have a health check
